FROM public.ecr.aws/lambda/nodejs:20 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM public.ecr.aws/lambda/nodejs:20 as prod

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package*.json ./

RUN npm install --omit=dev

COPY --from=build /app/build ./build

CMD ["build/lambda.handler"]