name: Deploy Audit Service

on:
  push:
    branches:
      - main
    paths:
      - 'audit-service/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lambda/audit-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS_ACCESS_KEY

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login To ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.lambda \
          -t $ECR_REPOSITORY \
          ./audit-service

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:latest \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest